#!/bin/sh

###############################################################################
#
# File:         plcmd
# CVS:          $Id: plcmd,v 1.3 2004/01/27 20:48:41 sbirrer Exp $
# Description:  Executes a list of commands on several nodes in parallel
# Author:       Stefan Birrer
#               Northwestern University
# Language:     bash
# Status:       Released
#
# (C) Copyright 2004, Northwestern University, all rights reserved.
#
###############################################################################

CMD=$1;
LIST=$2;
ID=$3;
N_THREADS=50;
PROG=`basename $0`;
LOCK="${TMP:-/tmp}/${PROG}.lock";
SEM="${TMP:-/tmp}/${PROG}.${ID}.lock";
RC="${HOME}/.nixesrc";

#register clean up handler
DONE=0
function cleanUp()
{
	if [[ ${DONE} == 0 ]]; then
		${KILL} 0;
	fi;
}

#Check arguments
if [[ $# == 0 || $# > 3 ]]; then
	echo "usage: $0 command list-file"
	exit 1;
fi;

if [ ! -f ${RC} ]; then
	echo "${RC}: cannot find configuration file";
	exit 1;
fi;

. ${RC} || exit 1;

IDENTITY=${IDENTITY:?"must be specified in ${RC}"};
SLICE=${SLICE:?"must be specified in ${RC}"};

if [ ! -r ${IDENTITY} ]; then
	echo "${IDENTITY}: access denied";
	exit 1;
fi;

eval EXEC=\$${CMD};

if [[ -z ${EXEC} ]]; then
	echo "${RC}: must specifiy command ${CMD}";
	exit 1;
fi;

#programms
TIMEOUT="timeout 1000"
SSH="ssh -i ${IDENTITY} -n -x -l ${SLICE}"
SYNC="wget -N -q"
RM="rm -f"
KILL="kill -n 9"
MKDIR="mkdir -p";
TIME="date +%s";

trap 'cleanUp' EXIT || exit 1;
	
if [[ $# == 2 ]]; then
	#start threads
	${RM} ${LOCK};
	i=0;
	locks="";
	while (( ${N_THREADS} - i )); do
		SEM="${TMP:-/tmp}/${PROG}.${i}.lock"
		${RM} ${SEM};
		locks="${locks} ${SEM}";
		lockfile -1 ${SEM};
		$0 ${CMD} ${LIST} ${i} &
		(( i=i+1 ));
	done;
	#wait for childs to terminate
	lockfile -1 ${locks};
	${RM} ${locks};
else
	i=0;
	for node in $(< ${LIST}); do
		(( cur=i%${N_THREADS} ));
		if [[ ${cur} == ${ID} ]]; then
			log="${TMP:-/tmp}/${node}.log";
			${RM} ${log};
			echo ${CMD} ${node} >> ${log};
			echo ${EXEC} >> ${log};
			echo >> ${log};
			
			t_start=$(${TIME});
			echo Connecting Node $i;
			${TIMEOUT} ${SSH} ${node} "${EXEC}" >> ${log} 2>&1;
			exit_code=$?;
			t_end=$(${TIME});
			(( total = ${t_end} - ${t_start} ));
			echo Command took ${total} seconds and returned ${exit_code} >> ${log}
			lockfile -1 ${LOCK};
			if [[ ${exit_code} == 0 ]]; then
				echo -e "${node} done\r";
			elif [[ ${exit_code} == 255 ]]; then
				echo $(< ${log});
				echo;		
			else
				echo -e "${node} failed (see ${log})\r";
			fi;
			${RM} ${LOCK};
		fi;
		(( i=i+1 ));
		sleep 3;
	done;
	${RM} ${SEM};
fi;
DONE=1;
