#!/bin/bash

# set variables
port=58888
cert_dir=certificates
root=`whoami`
user=`ls -l private_key | awk '{ print $4 }'`
device=tapipop

if [[ $root != "root" ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ -d $cert_dir ]]; then
  ./tunctl -d $device
  ./tunctl -u $user -t $device
  chmod 666 /dev/net/tun
  su $user -c "mono SocialVPN.exe brunet.config ipop.config $port off &> log.txt &"
else
  echo "Run ./setup as non-root"
  exit 1
fi

sleep 3
/sbin/dhclient -pf /var/run/dhclient.$device.pid -lf /var/lib/dhcp3/dhclient.$device.leases $device

echo "Point your browser to http://127.0.0.1:58888"
