#!/bin/bash

# set variables
cert_dir=certificates
root=`whoami`
device=tapipop
platform=linux
mac_path=/dev/tap0

if [[ -e $mac_path ]]; then
  platform=mac
fi

if [[ $root != root ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ -d $cert_dir ]]; then
  user=`ls -l private_key | awk '{ print $3 }'`
  if [[ $platform == linux ]]; then
    ./tunctl -d $device
    ./tunctl -u $user -t $device
    chmod 666 /dev/net/tun
  elif [[ $platform == mac ]]; then
    chmod 666 /dev/tap0
  fi
  su $user -c "mono SocialVPN.exe &> log.txt &"
else
  echo "Run ./setup as non-root"
  exit 1
fi

sleep 3

if [[ $platform == linux ]]; then
  /sbin/dhclient -pf /var/run/dhclient.$device.pid -lf /var/lib/dhcp3/dhclient.$device.leases $device
elif [[  $platform == mac ]]; then
  /usr/sbin/ipconfig set tap0 DHCP
  /sbin/ifconfig tap0 mtu 1200
fi

echo "Point your browser to http://127.0.0.1:58888"
