//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SocialVPN")]
[assembly: AssemblyDescription("The Social Virtual Private Network")]
[assembly: AssemblyCompany("ACIS Lab - University of Florida")]
[assembly: AssemblyProduct("socialvpn")]
[assembly: AssemblyCopyright("Copyright (c) University of Florida")]
[assembly: AssemblyVersion("0.3.1")]

