using Brunet.Util;

namespace Brunet.Messaging {


/**
 * Handles replies in the Request/Reply protocol.
 * @see ReqrepManager
 */
public interface IReplyHandler {

  /**
   * This method is called when a reply comes back (maybe
   * more than once).
   *
   * @param man the ReqrepManager managing this node
   * @param mid the identifier request/reply
   * @param type the PType of the payload
   * @param payload the data of the reply
   * @param returnpath a sender to communicate with the node that sent the reply
   * @param statistics statistical information about the request
   * @param state the state that was given to SendRequest is returned here
   * @return true if we should continue listening for replies,
   *          false if we should ignore future replies.
   */
  bool HandleReply(ReqrepManager man, ReqrepManager.ReqrepType rt,
		   int mid,
		   PType prot,
		   MemBlock payload, ISender returnpath,
		   ReqrepManager.Statistics statistics,
		   object state);
  /**
   * @param man  the ReqrepManager managing this node
   * @param message_number the number for this request/reply
   * @param err The type of Error that has occured.
   * @param returnpath ISender to communicate with the node that sent the
   *        reply (may be null if it was generated by ReqrepManager).
   * @param state the state that was given to SendRequest is returned here
   */
  void HandleError(ReqrepManager man, int message_number,
		   ReqrepManager.ReqrepError err, ISender returnpath, object state);
}
	
}
